/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trAndpl.gui;

import java.sql.SQLException;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.swing.JOptionPane;
import trAndpl.Dao.HrDAO;
import trAndpl.Dao.SendMails;
import trAndpl.pojo.CurrentUser;
import trAndpl.pojo.HrPojo;

/**
 *
 * @author Dell
 */
public class AdminAddNewHrFrame extends javax.swing.JFrame {

    private String Password;
    private String ConfrmPwd;
    public AdminAddNewHrFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblName.setText(CurrentUser.getName());
        loadId();
    }
    private void loadId(){
        try{
            int hrId=HrDAO.getNewHrId();
            lblHrId.setText("Hr-"+hrId);
        }
         catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Db Error","Error!", JOptionPane.ERROR_MESSAGE);   
            ex.printStackTrace();
            
        }
    }
    private boolean validateInputs(){
        Password=String.valueOf(TxtPwd.getPassword()).trim();
        ConfrmPwd=String.valueOf(TxtConfrPwd.getPassword());
        int index=jcProf.getSelectedIndex();
        if(TxtName.getText().isEmpty()||TxtEmail.getText().isEmpty()||TxtMob.getText().isEmpty()||TxtCompany.getText().isEmpty()||Password.isEmpty()||ConfrmPwd.isEmpty()||index==0)
           return false;
        
        return true;
    }
    private boolean MatchPassword(){
        return Password.equals(ConfrmPwd);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnLogout = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddNewHrBtn = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblHrId = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jcProf = new javax.swing.JComboBox<>();
        TxtName = new javax.swing.JTextField();
        TxtMob = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TxtPwd = new javax.swing.JPasswordField();
        TxtConfrPwd = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TxtCompany = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 245, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 980, 200));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setText("Welcome ,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 50));

        BtnLogout.setBackground(new java.awt.Color(204, 204, 255));
        BtnLogout.setText("Logout");
        BtnLogout.setOpaque(false);
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 650, 149, -1));

        lblName.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblName.setText("Swapnil");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 170, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/addNewEmp.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 180, 190));

        AddNewHrBtn.setBackground(new java.awt.Color(204, 204, 255));
        AddNewHrBtn.setText("Add New HR");
        AddNewHrBtn.setOpaque(false);
        AddNewHrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewHrBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AddNewHrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 285, 39));

        BtnBack.setBackground(new java.awt.Color(204, 204, 255));
        BtnBack.setText("Back");
        BtnBack.setOpaque(false);
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 130, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 1000, 20));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel5.setText("Hr id :-");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 287, -1, -1));

        lblHrId.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        lblHrId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblHrId, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 287, 126, 25));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel7.setText("Company name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 287, -1, -1));

        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 319, 2815, 11));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel14.setText("Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        jLabel16.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel16.setText("Name");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        jLabel17.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel17.setText("Email");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        jLabel19.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel19.setText("Profession in");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 120, -1));

        jLabel20.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel20.setText("Mobile No");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));

        jLabel21.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel21.setText("Confirm Password");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, -1, -1));

        jcProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Profession", "Developer", "Technical", "Aptitude", "Digital Marketing" }));
        jcProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcProfActionPerformed(evt);
            }
        });
        jPanel1.add(jcProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 265, -1));

        TxtName.setBackground(new java.awt.Color(173, 192, 234));
        TxtName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtName.setBorder(null);
        TxtName.setOpaque(false);
        jPanel1.add(TxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 249, 20));

        TxtMob.setBackground(new java.awt.Color(173, 192, 234));
        TxtMob.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtMob.setBorder(null);
        TxtMob.setOpaque(false);
        TxtMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMobActionPerformed(evt);
            }
        });
        jPanel1.add(TxtMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 250, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_915734271.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 289, -1));

        TxtEmail.setBackground(new java.awt.Color(173, 192, 234));
        TxtEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtEmail.setBorder(null);
        TxtEmail.setOpaque(false);
        TxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 240, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, -1, -1));

        TxtPwd.setBackground(new java.awt.Color(173, 192, 234));
        TxtPwd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtPwd.setBorder(null);
        TxtPwd.setOpaque(false);
        jPanel1.add(TxtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 250, 20));

        TxtConfrPwd.setBackground(new java.awt.Color(173, 192, 234));
        TxtConfrPwd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtConfrPwd.setBorder(null);
        TxtConfrPwd.setOpaque(false);
        jPanel1.add(TxtConfrPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 250, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, -1, -1));

        TxtCompany.setBackground(new java.awt.Color(243, 245, 254));
        TxtCompany.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtCompany.setBorder(null);
        TxtCompany.setOpaque(false);
        jPanel1.add(TxtCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 160, 20));

        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        new AdminHrModuleFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void AddNewHrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewHrBtnActionPerformed
       if(validateInputs()==false){
           JOptionPane.showMessageDialog(null, "Please fill all the fields!", "Error!", JOptionPane.ERROR_MESSAGE);
           return;
       }
       if(TxtMob.getText().length()>10||TxtMob.getText().length()<10){
            JOptionPane.showMessageDialog(null, "Please Input 10 digits Mobile No!");
            return;
          }
       if(MatchPassword()==false){
           JOptionPane.showMessageDialog(null, "Passwords do not match!", "Error!", JOptionPane.ERROR_MESSAGE);
           return;
       }
       try{
           HrPojo hr=new HrPojo();
           hr.setUserId(TxtEmail.getText().trim().toUpperCase());
           hr.setHrId(lblHrId.getText().trim());
           hr.setHrname(TxtName.getText().trim());
           hr.setCompanyName(TxtCompany.getText().trim());
           hr.setPassword(Password);
           hr.setPhone(TxtMob.getText().trim());
           hr.setProfession(jcProf.getSelectedItem().toString());
           hr.setType("Hr");
           int result=HrDAO.addNewHr(hr);
           if(result==1){
              JOptionPane.showMessageDialog(null, "Record Added", "Success!", JOptionPane.INFORMATION_MESSAGE); 
               ClearAll();
               try{
                InternetAddress[]recipients=InternetAddress.parse(String.valueOf(hr.getUserId())+"");
                Message m=SendMails.Sends();
                m.setRecipients(Message.RecipientType.TO,recipients);
                m.setSubject("Notification From Tnp Application");
                m.setText("Hello "+hr.getHrname()+",\nWarm Welcome in SCALIVE Traning And Placement Application.\n"
                          +"Your Login Credentials-\n\n" 
                          +"Hr Id - "+hr.getHrId()+"\n"
                          +"Email :-"+hr.getUserId()+"\n"
                          +"Password :- "+hr.getPassword()+"\n"
                          +"\nWarm Regards" 
                          +"\nSCALIVE"
                          +"\nTraning And Placement Application");
                Transport.send(m);
              }
                catch (MessagingException e) {
                   e.printStackTrace();
                
                }
                        
              return;
            }
             else if(result==-1){
              JOptionPane.showMessageDialog(null, "This Email Id is Already Registered!", "Error!", JOptionPane.ERROR_MESSAGE); 
               ClearAll();
               return;
           }
           else{
              JOptionPane.showMessageDialog(null, "Cannot add the Record!", "Error!", JOptionPane.ERROR_MESSAGE); 
              ClearAll();
              return;
           }
          
       }
       catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Db Error","Error!", JOptionPane.ERROR_MESSAGE); 
            ClearAll();
            ex.printStackTrace();
       }
     
       
    }//GEN-LAST:event_AddNewHrBtnActionPerformed

    private void ClearAll(){
        TxtName.setText(" ");
        TxtEmail.setText(" ");
        TxtMob.setText(" ");
        TxtCompany.setText(" ");
        TxtPwd.setText("");
        TxtConfrPwd.setText("");
        jcProf.setSelectedIndex(0);
      }
    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void jcProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcProfActionPerformed

    private void TxtMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMobActionPerformed

    private void TxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddNewHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddNewHrFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewHrBtn;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JTextField TxtCompany;
    private javax.swing.JPasswordField TxtConfrPwd;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtMob;
    private javax.swing.JTextField TxtName;
    private javax.swing.JPasswordField TxtPwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcProf;
    private javax.swing.JLabel lblHrId;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
