/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trAndpl.gui;

import java.sql.SQLException;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import trAndpl.Dao.UserDAO;
import trAndpl.pojo.CurrentUser;
import trAndpl.pojo.HrPojo;

/**
 *
 * @author Dell
 */
public class AdminModifyHrFrame extends javax.swing.JFrame {

    private Map<String,HrPojo> allHr;
    private String Password;
    public AdminModifyHrFrame() {
        initComponents();
        lblName.setText(CurrentUser.getName());
        setLocationRelativeTo(null);
        LoadHrDetails();
    }
    private boolean validateInputs(){
        char[]pwd=TxtNewPwd.getPassword();
        char[]conPwd=TxtConfrmPwd.getPassword();
        if(pwd.length<6||conPwd.length<6){
            JOptionPane.showMessageDialog(null, "Password must be atleast 6 characters long!");
            return false;
        }
        Password=String.valueOf(pwd);
        String conpassword=String.valueOf(conPwd);
        if(Password.equals(conpassword)==false){
            JOptionPane.showMessageDialog(null, "Password not matching!");
            return false;
           }
        return true;
    }
    private void clearText(){
        TxtNewPwd.setText("");
        TxtConfrmPwd.setText("");
        jcAllUserId.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnLogout = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ModifyHrbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblHrname = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcAllUserId = new javax.swing.JComboBox<>();
        TxtHrId = new javax.swing.JTextField();
        TxtNewPwd = new javax.swing.JPasswordField();
        TxtConfrmPwd = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 245, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 980, 200));

        jLabel3.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel3.setText("Welcome ,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 50));

        BtnLogout.setBackground(new java.awt.Color(204, 204, 255));
        BtnLogout.setText("Logout");
        BtnLogout.setOpaque(false);
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 650, 149, -1));

        lblName.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        lblName.setText("Swapnil");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 170, 30));

        BtnBack.setBackground(new java.awt.Color(204, 204, 255));
        BtnBack.setText("Back");
        BtnBack.setOpaque(false);
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 130, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 1000, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/modify-emp.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 190, 200));

        ModifyHrbtn.setBackground(new java.awt.Color(204, 204, 255));
        ModifyHrbtn.setText("Modify Changes of HR");
        ModifyHrbtn.setOpaque(false);
        ModifyHrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyHrbtnActionPerformed(evt);
            }
        });
        jPanel1.add(ModifyHrbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 285, 39));

        jLabel5.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel5.setText("User id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        lblHrname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(lblHrname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 220, 30));

        jLabel7.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel7.setText("New Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, -1));

        jLabel9.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel9.setText("Hr id");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 60, -1));

        jLabel12.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel12.setText("Hr Name -");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        jLabel13.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel13.setText("Confirm Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, -1, -1));

        jcAllUserId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jcAllUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcAllUserIdActionPerformed(evt);
            }
        });
        jPanel1.add(jcAllUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 290, 30));

        TxtHrId.setBackground(new java.awt.Color(173, 192, 234));
        TxtHrId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtHrId.setBorder(null);
        jPanel1.add(TxtHrId, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 280, -1));

        TxtNewPwd.setBackground(new java.awt.Color(173, 192, 234));
        TxtNewPwd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtNewPwd.setBorder(null);
        jPanel1.add(TxtNewPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 230, -1));

        TxtConfrmPwd.setBackground(new java.awt.Color(173, 192, 234));
        TxtConfrmPwd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtConfrmPwd.setBorder(null);
        jPanel1.add(TxtConfrmPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 250, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 330, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, -1, -1));

        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 320, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        new AdminHrModuleFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void ModifyHrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyHrbtnActionPerformed
        if(!validateInputs()){
            return;
        }
        try{
            boolean result=UserDAO.updatePwd(jcAllUserId.getSelectedItem().toString(), Password);
            if(result){
                JOptionPane.showMessageDialog(null, "Password Change Successfully","Done", JOptionPane.INFORMATION_MESSAGE);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Sorry! Could not Change the Password","Unsuccesfull", JOptionPane.ERROR_MESSAGE);
            }
            clearText();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Db Error","Error!", JOptionPane.ERROR_MESSAGE);   
            ex.printStackTrace();
            
        }

    }//GEN-LAST:event_ModifyHrbtnActionPerformed

    private void jcAllUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcAllUserIdActionPerformed
      String userId=(String)jcAllUserId.getSelectedItem();
      HrPojo hr=allHr.get(userId);
      TxtHrId.setText(hr.getHrId());
      lblHrname.setText(hr.getHrname());
      
    }//GEN-LAST:event_jcAllUserIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminModifyHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminModifyHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminModifyHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminModifyHrFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminModifyHrFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton ModifyHrbtn;
    private javax.swing.JPasswordField TxtConfrmPwd;
    private javax.swing.JTextField TxtHrId;
    private javax.swing.JPasswordField TxtNewPwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcAllUserId;
    private javax.swing.JLabel lblHrname;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables

    private void LoadHrDetails() {
        try{
            allHr=UserDAO.getAllHrList();
            Set<String> keys=allHr.keySet();
            for(String UserId:keys){
                jcAllUserId.addItem(UserId);
            }
        }
         catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Db Error","Error!", JOptionPane.ERROR_MESSAGE);   
            ex.printStackTrace();
            
        }
      }
}
