/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trAndpl.gui;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import trAndpl.Dao.HrDAO;
import trAndpl.Dao.JobDAO;
import trAndpl.pojo.CurrentUser;
import trAndpl.pojo.JobPojo;

/**
 *
 * @author Dell
 */
public class HrEditJobFrame extends javax.swing.JFrame {

    /**
     * Creates new form HrEditJobFrame
     */
    private JobPojo job;
    public HrEditJobFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblName.setText(CurrentUser.getName());

    }
        public HrEditJobFrame(JobPojo job){
        this();
        this.job=job;
        showJobDetails();
        
    }
    private void showJobDetails(){
        String companyName="";
        try{
           companyName=HrDAO.getCompanyNameById(job.getHrId());           
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"SQL Error!","DB Problem,",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            return;
        }
        lblJobId.setText(job.getJobId());
        TxtJobTitle.setText(job.getJobTitle());
        TxtCompnyname.setText(companyName);
        String []allSkills=job.getTags().split(",");
        TxtSkill1.setText(allSkills[0]);
        TxtSkill2.setText(allSkills[1]);
        TxtSkill3.setText(allSkills[2]);
        TxtSkill4.setText(allSkills[3]);
        
    }
private boolean validateInputs(){
        if(TxtJobTitle.getText().trim().isEmpty()||TxtSkill1.getText().trim().isEmpty()||TxtSkill2.getText().trim().isEmpty()||TxtSkill3.getText().trim().isEmpty()||TxtSkill4.getText().trim().isEmpty())
            return false;
        return true;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnLogout = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        BtnSaveChanges = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        TxtJobTitle = new javax.swing.JTextField();
        TxtCompnyname = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblJobId = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtSkill3 = new javax.swing.JTextField();
        TxtSkill4 = new javax.swing.JTextField();
        TxtSkill2 = new javax.swing.JTextField();
        TxtSkill1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 245, 254));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1000, 200));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setText("Welcome ,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 50));

        BtnLogout.setBackground(new java.awt.Color(204, 204, 255));
        BtnLogout.setText("Logout");
        BtnLogout.setOpaque(false);
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 670, 149, -1));

        lblName.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblName.setText("Swapnil");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 170, 30));

        BtnSaveChanges.setBackground(new java.awt.Color(204, 204, 255));
        BtnSaveChanges.setText("Saves Changes");
        BtnSaveChanges.setOpaque(false);
        BtnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveChangesActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSaveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, 285, 39));

        BtnBack.setBackground(new java.awt.Color(204, 204, 255));
        BtnBack.setText("Back");
        BtnBack.setOpaque(false);
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 130, -1));

        TxtJobTitle.setBackground(new java.awt.Color(173, 192, 234));
        TxtJobTitle.setBorder(null);
        jPanel1.add(TxtJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 412, 230, 20));

        TxtCompnyname.setBackground(new java.awt.Color(173, 192, 234));
        TxtCompnyname.setBorder(null);
        jPanel1.add(TxtCompnyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 230, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 990, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/JobPng.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 310, 310));

        jLabel6.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel6.setText("Company Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel5.setText("Job Title");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel11.setText("Skills Required:-");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        lblJobId.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jPanel1.add(lblJobId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 90, 30));

        jLabel7.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel7.setText("Job Id:-");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 70, 30));

        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 720, 140));

        TxtSkill3.setBackground(new java.awt.Color(173, 192, 234));
        jPanel1.add(TxtSkill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 210, 30));

        TxtSkill4.setBackground(new java.awt.Color(173, 192, 234));
        jPanel1.add(TxtSkill4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 210, 30));

        TxtSkill2.setBackground(new java.awt.Color(173, 192, 234));
        TxtSkill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSkill2ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtSkill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 210, 30));

        TxtSkill1.setBackground(new java.awt.Color(173, 192, 234));
        jPanel1.add(TxtSkill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveChangesActionPerformed
      if(!validateInputs()){
            JOptionPane.showMessageDialog(null,"Please Fill All The Fields","Empty Data!!",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        job.setJobTitle(TxtJobTitle.getText().trim());
        job.setTags(TxtSkill1.getText().trim()+","+TxtSkill2.getText().trim()+","+TxtSkill3.getText().trim()+","+TxtSkill4.getText().trim());
        try{
            boolean result=JobDAO.editJobByJobId(job);
            if(result){
                JOptionPane.showMessageDialog(null,"Job Successfully Edited","Success",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
             JOptionPane.showMessageDialog(null,"Job Not Edited","Editing Failed!",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"SQL Error!","DB Problem,",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            return;
        }
        


    }//GEN-LAST:event_BtnSaveChangesActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        new HrChooseJobForEditingFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void TxtSkill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSkill2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSkill2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrEditJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrEditJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrEditJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrEditJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrEditJobFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnSaveChanges;
    private javax.swing.JTextField TxtCompnyname;
    private javax.swing.JTextField TxtJobTitle;
    private javax.swing.JTextField TxtSkill1;
    private javax.swing.JTextField TxtSkill2;
    private javax.swing.JTextField TxtSkill3;
    private javax.swing.JTextField TxtSkill4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJobId;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
