/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trAndpl.gui;

import trAndpl.pojo.CurrentUser;

/**
 *
 * @author Dell
 */
public class HrOptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form HrOptionsFrame
     */
    public HrOptionsFrame() {
        initComponents();
        setLocationRelativeTo(null);
        lblName.setText(CurrentUser.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnjobMod = new javax.swing.JButton();
        BtnViewAllParti = new javax.swing.JButton();
        BtnViewTestResult = new javax.swing.JButton();
        BtnViewAllOpenJobs = new javax.swing.JButton();
        BtnLogout = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 245, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/World-Map.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 61, 967, 216));

        jLabel3.setFont(new java.awt.Font("Noteworthy", 1, 24)); // NOI18N
        jLabel3.setText("Welcome ,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 284, -1, -1));

        BtnjobMod.setBackground(new java.awt.Color(204, 204, 255));
        BtnjobMod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnjobMod.setText("job Module");
        BtnjobMod.setOpaque(false);
        BtnjobMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnjobModActionPerformed(evt);
            }
        });
        jPanel1.add(BtnjobMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 385, 316, 40));

        BtnViewAllParti.setBackground(new java.awt.Color(204, 204, 255));
        BtnViewAllParti.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnViewAllParti.setText("View All Participants");
        BtnViewAllParti.setOpaque(false);
        BtnViewAllParti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewAllPartiActionPerformed(evt);
            }
        });
        jPanel1.add(BtnViewAllParti, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 470, 316, 40));

        BtnViewTestResult.setBackground(new java.awt.Color(204, 204, 255));
        BtnViewTestResult.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnViewTestResult.setText("View Test Result");
        BtnViewTestResult.setOpaque(false);
        BtnViewTestResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewTestResultActionPerformed(evt);
            }
        });
        jPanel1.add(BtnViewTestResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 563, 316, 39));

        BtnViewAllOpenJobs.setBackground(new java.awt.Color(204, 204, 255));
        BtnViewAllOpenJobs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnViewAllOpenJobs.setText("View All Open Jobs");
        BtnViewAllOpenJobs.setOpaque(false);
        BtnViewAllOpenJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewAllOpenJobsActionPerformed(evt);
            }
        });
        jPanel1.add(BtnViewAllOpenJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 665, 316, 39));

        BtnLogout.setBackground(new java.awt.Color(204, 204, 255));
        BtnLogout.setText("Logout");
        BtnLogout.setOpaque(false);
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 711, 122, -1));

        lblName.setFont(new java.awt.Font("Noteworthy", 1, 24)); // NOI18N
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 284, 164, 39));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/worlp-map-in-black-h9i.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 335, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnjobModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnjobModActionPerformed
         new HrJobOptionsFrame().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_BtnjobModActionPerformed

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnViewAllPartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewAllPartiActionPerformed
        new HrViewAllParticipantsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnViewAllPartiActionPerformed

    private void BtnViewTestResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewTestResultActionPerformed
       new HrViewAllParticipantsResultFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnViewTestResultActionPerformed

    private void BtnViewAllOpenJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewAllOpenJobsActionPerformed
        new HrViewAllOpenJobsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnViewAllOpenJobsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrOptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnViewAllOpenJobs;
    private javax.swing.JButton BtnViewAllParti;
    private javax.swing.JButton BtnViewTestResult;
    private javax.swing.JButton BtnjobMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
