/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trAndpl.gui;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import trAndpl.Dao.ParticipantsDAO;
import trAndpl.pojo.CurrentUser;
import trAndpl.pojo.ParticipantsPojo;

/**
 *
 * @author Dell
 */
public class HrViewUserProfileFrame extends javax.swing.JFrame {

    private String pid;
    public HrViewUserProfileFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }
  
    public HrViewUserProfileFrame(String pid) {
        this();
        this.pid=pid;
        lblPid.setText(this.pid); 
        this.setVisible(true);
        LoadUserProfile();
     }
    private void LoadUserProfile()
    {
        try{
              ParticipantsPojo pt=ParticipantsDAO.ViewUserProfile(pid);
              TxtName.setText(pt.getName());
              TxtMail.setText(pt.getUserId());
              TxtMob.setText(pt.getPhone());
              TxtSkill1.setText(pt.getSkills());
              TxtQualifications.setText(pt.getQualifications());
              TxtPwd.setEchoChar((char)0);
              TxtPwd.setText(pt.getPassword());
              
            }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error In Quiz", "Error!!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
            
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TxtQualifications = new javax.swing.JTextField();
        TxtPwd = new javax.swing.JPasswordField();
        TxtMail = new javax.swing.JTextField();
        TxtName = new javax.swing.JTextField();
        TxtMob = new javax.swing.JTextField();
        TxtSkill1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtnLoginPage = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPid = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 245, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtQualifications.setEditable(false);
        TxtQualifications.setBackground(new java.awt.Color(173, 192, 234));
        TxtQualifications.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(TxtQualifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 910, 60));

        TxtPwd.setEditable(false);
        TxtPwd.setBackground(new java.awt.Color(173, 192, 234));
        TxtPwd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtPwd.setBorder(null);
        jPanel1.add(TxtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 390, -1));

        TxtMail.setEditable(false);
        TxtMail.setBackground(new java.awt.Color(173, 192, 234));
        TxtMail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtMail.setBorder(null);
        jPanel1.add(TxtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 350, 20));

        TxtName.setEditable(false);
        TxtName.setBackground(new java.awt.Color(173, 192, 234));
        TxtName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtName.setBorder(null);
        jPanel1.add(TxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 390, -1));

        TxtMob.setEditable(false);
        TxtMob.setBackground(new java.awt.Color(173, 192, 234));
        TxtMob.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtMob.setBorder(null);
        TxtMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMobActionPerformed(evt);
            }
        });
        jPanel1.add(TxtMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 350, 20));

        TxtSkill1.setEditable(false);
        TxtSkill1.setBackground(new java.awt.Color(173, 192, 234));
        TxtSkill1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(TxtSkill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 910, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/World-Map.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 960, 210));

        BtnLoginPage.setBackground(new java.awt.Color(204, 204, 255));
        BtnLoginPage.setText("Logout");
        BtnLoginPage.setOpaque(false);
        BtnLoginPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginPageActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLoginPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 610, 170, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Name:-");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 180, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Skills:-");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 170, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Participant id:-");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 30));

        lblPid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(lblPid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 70, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Qualifications:-");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 170, -1));

        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 1000, 180));

        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 470, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Mobile No:-");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Email id:-");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("Password:-");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 460, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMobActionPerformed

    private void BtnLoginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginPageActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnLoginPageActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new HrViewAllParticipantsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrViewUserProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrViewUserProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrViewUserProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrViewUserProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrViewUserProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLoginPage;
    private javax.swing.JTextField TxtMail;
    private javax.swing.JTextField TxtMob;
    private javax.swing.JTextField TxtName;
    private javax.swing.JPasswordField TxtPwd;
    private javax.swing.JTextField TxtQualifications;
    private javax.swing.JTextField TxtSkill1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPid;
    // End of variables declaration//GEN-END:variables
}
