/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trAndpl.gui;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import trAndpl.Dao.UserDAO;
import trAndpl.pojo.CurrentUser;
import trAndpl.pojo.UserPojo;

/**
 *
 * @author Dell
 */
public class LoginFrame extends javax.swing.JFrame {

    private String userId;
    private String password;
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
         private String validateUser(){
             if(jrbAdmin.isSelected())
                 return "Admin";
             else if(jrbHr.isSelected())
                 return "Hr";
             else if(jrbPt.isSelected())
                 return "Students";
             else
                 return null;
             
         }
         private boolean validateInputs(){
         userId=TextMail.getText().trim();
         char []pwd=TextPwd.getPassword();
         if(userId.isEmpty()||pwd.length==0)
             return false;
         password=String.valueOf(pwd);
         return true;
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextPwd = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jrbAdmin = new javax.swing.JRadioButton();
        BtnLogin = new javax.swing.JButton();
        BtnSignUp = new javax.swing.JButton();
        jrbHr = new javax.swing.JRadioButton();
        jrbPt = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextMail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 245, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Email or User id :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Password :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        TextPwd.setBackground(new java.awt.Color(173, 192, 234));
        TextPwd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TextPwd.setBorder(null);
        TextPwd.setOpaque(false);
        jPanel1.add(TextPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 347, 400, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 329, 450, 50));

        buttonGroup1.add(jrbAdmin);
        jrbAdmin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrbAdmin.setText("Admin");
        jrbAdmin.setOpaque(false);
        jPanel1.add(jrbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 100, 20));

        BtnLogin.setBackground(new java.awt.Color(204, 204, 255));
        BtnLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnLogin.setText("Login");
        BtnLogin.setOpaque(false);
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 160, 30));

        BtnSignUp.setBackground(new java.awt.Color(204, 204, 255));
        BtnSignUp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnSignUp.setText("Sign Up");
        BtnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 160, 30));

        buttonGroup1.add(jrbHr);
        jrbHr.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrbHr.setText("Company Hr");
        jrbHr.setOpaque(false);
        jrbHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbHrActionPerformed(evt);
            }
        });
        jPanel1.add(jrbHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 120, 20));

        buttonGroup1.add(jrbPt);
        jrbPt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrbPt.setText("Students");
        jrbPt.setOpaque(false);
        jrbPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPtActionPerformed(evt);
            }
        });
        jPanel1.add(jrbPt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 100, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Select User Type :-");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 440, 130));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/homePage.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 610, 510));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TextMail.setBackground(new java.awt.Color(173, 192, 234));
        TextMail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TextMail.setBorder(null);
        TextMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMailActionPerformed(evt);
            }
        });
        jPanel1.add(TextMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 263, 360, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 500, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbPtActionPerformed

    private void jrbHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbHrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbHrActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        if(validateInputs()==false){
            JOptionPane.showMessageDialog(null, "Please fill all the fields", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String type=validateUser();
        if(type==null){
            JOptionPane.showMessageDialog(null, "Please Select a user type", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        UserPojo user=new UserPojo();
        user.setUserid(userId.toUpperCase().trim());
        user.setPassword(password);
        user.setType(type);
        try{
            boolean result=UserDAO.ValidateUser(user);
            if(result){
                 if(CurrentUser.getType().equals("Admin")){
                     JOptionPane.showMessageDialog(null, "Welcome Admin "+CurrentUser.getName(),"Success", JOptionPane.INFORMATION_MESSAGE);
                     new AdminOptionsFrame().setVisible(result);
                     this.dispose();
                 }
                else if(CurrentUser.getType().equals("Hr")){
                     JOptionPane.showMessageDialog(null, "Welcome Hr "+CurrentUser.getName(),"Success", JOptionPane.INFORMATION_MESSAGE);
                     new HrOptionsFrame().setVisible(result);
                     this.dispose();
                }
                else  {
                     JOptionPane.showMessageDialog(null, "Welcome Student "+CurrentUser.getName(),"Success", JOptionPane.INFORMATION_MESSAGE);
                     new ParticipantsOptionFrame().setVisible(result);
                     this.dispose();
                 
                }
            }
            else{
                      JOptionPane.showMessageDialog(null, "Invalid UserId or Password or Usertype","Error!", JOptionPane.ERROR_MESSAGE);   
                      return;
              }
           }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Db Error","Error!", JOptionPane.ERROR_MESSAGE);   
            ex.printStackTrace();
            
        }
        
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void TextMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMailActionPerformed

    private void BtnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignUpActionPerformed
        new SignUpFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton BtnSignUp;
    private javax.swing.JTextField TextMail;
    private javax.swing.JPasswordField TextPwd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbAdmin;
    private javax.swing.JRadioButton jrbHr;
    private javax.swing.JRadioButton jrbPt;
    // End of variables declaration//GEN-END:variables
}
