/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trAndpl.gui;

import trAndpl.pojo.CurrentUser;

/**
 *
 * @author Dell
 */
public class ParticipantsOptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form ParticipantsOptionFrame
     */
    public ParticipantsOptionFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblName.setText(CurrentUser.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnEditProfile = new javax.swing.JButton();
        BtnViewAllAvaiJobs = new javax.swing.JButton();
        BtnViewAllAppliedJobs = new javax.swing.JButton();
        VBtnViewAllComJobs = new javax.swing.JButton();
        BtnLogout = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 245, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1020, 216));

        jLabel3.setFont(new java.awt.Font("Noteworthy", 1, 24)); // NOI18N
        jLabel3.setText("Welcome ,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        BtnEditProfile.setBackground(new java.awt.Color(204, 204, 255));
        BtnEditProfile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnEditProfile.setText("Edit Profile");
        BtnEditProfile.setOpaque(false);
        BtnEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditProfileActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 385, 316, 40));

        BtnViewAllAvaiJobs.setBackground(new java.awt.Color(204, 204, 255));
        BtnViewAllAvaiJobs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnViewAllAvaiJobs.setText("View All Available Jobs");
        BtnViewAllAvaiJobs.setOpaque(false);
        BtnViewAllAvaiJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewAllAvaiJobsActionPerformed(evt);
            }
        });
        jPanel1.add(BtnViewAllAvaiJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 471, 316, 40));

        BtnViewAllAppliedJobs.setBackground(new java.awt.Color(204, 204, 255));
        BtnViewAllAppliedJobs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnViewAllAppliedJobs.setText("View All Applied Jobs");
        BtnViewAllAppliedJobs.setOpaque(false);
        BtnViewAllAppliedJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewAllAppliedJobsActionPerformed(evt);
            }
        });
        jPanel1.add(BtnViewAllAppliedJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 571, 316, 39));

        VBtnViewAllComJobs.setBackground(new java.awt.Color(204, 204, 255));
        VBtnViewAllComJobs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VBtnViewAllComJobs.setText("View All completed Jobs");
        VBtnViewAllComJobs.setOpaque(false);
        VBtnViewAllComJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VBtnViewAllComJobsActionPerformed(evt);
            }
        });
        jPanel1.add(VBtnViewAllComJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 667, 316, 39));

        BtnLogout.setBackground(new java.awt.Color(204, 204, 255));
        BtnLogout.setText("Logout");
        BtnLogout.setOpaque(false);
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 710, 122, -1));

        lblName.setFont(new java.awt.Font("Noteworthy", 1, 24)); // NOI18N
        lblName.setText("Swapnil");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 164, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/new/ptHomeImg.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, 359));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditProfileActionPerformed
      new PtEditProfileFrame().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_BtnEditProfileActionPerformed

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void VBtnViewAllComJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VBtnViewAllComJobsActionPerformed
       new PtViewAllCompletedJobsFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_VBtnViewAllComJobsActionPerformed

    private void BtnViewAllAvaiJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewAllAvaiJobsActionPerformed
       new PtViewAllAvailableJobsFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnViewAllAvaiJobsActionPerformed

    private void BtnViewAllAppliedJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewAllAppliedJobsActionPerformed
       new PtViewAllAppliedJobsFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnViewAllAppliedJobsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParticipantsOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParticipantsOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParticipantsOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParticipantsOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParticipantsOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditProfile;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnViewAllAppliedJobs;
    private javax.swing.JButton BtnViewAllAvaiJobs;
    private javax.swing.JButton VBtnViewAllComJobs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
