/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trAndpl.gui;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import trAndpl.Dao.ParticipantsDAO;
import trAndpl.Dao.UserDAO;
import trAndpl.pojo.CurrentUser;
import trAndpl.pojo.ParticipantsPojo;

/**
 *
 * @author Dell
 */
public class PtEditProfileFrame extends javax.swing.JFrame {

    private File file;
    private String oldpwd,npwd,cnfpwd;
    public PtEditProfileFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        PwdPanel.setVisible(false);
        ResumePanel.setVisible(false);
        loadData();
    }
     private void loadData(){
        try{
            ParticipantsPojo pt=ParticipantsDAO.getParticipantById(CurrentUser.getId());
            TxtName.setText(pt.getName());
            TxtMail.setText(pt.getUserId());
            TxtMobNo.setText(pt.getPhone());
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error In Edit Profile", "Error!!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
      private boolean validateInputs(){
        char []arroldpwd=TxtCurPwd.getPassword();
        char []arrnpwd=TxtNewPwd.getPassword();
        char []arrcnfrmpwd=TxtConPwd.getPassword();
        if(arroldpwd.length==0||arrnpwd.length==0||arrcnfrmpwd.length==0)
            return false;
        oldpwd=String.valueOf(arroldpwd);
        npwd=String.valueOf(arrnpwd);
        cnfpwd=String.valueOf(arrcnfrmpwd);
        return true;
    }
    private boolean matchPasswords(){
        return npwd.equals(cnfpwd);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        TxtMobNo = new javax.swing.JTextField();
        TxtMail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblJobId = new javax.swing.JLabel();
        PwdPanel = new javax.swing.JPanel();
        TxtConPwd = new javax.swing.JPasswordField();
        TxtCurPwd = new javax.swing.JPasswordField();
        TxtNewPwd = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CheckPwd = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        ResumePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TxtFilePath = new javax.swing.JTextField();
        BtnBrowserFile = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CheckResume = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        BtnDiscardChanges = new javax.swing.JButton();
        BtnSaveChanges = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(243, 245, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/transparent logo.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(243, 245, 254));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/World-Map.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 220));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Name:-");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 100, 20));

        TxtName.setBackground(new java.awt.Color(173, 192, 234));
        TxtName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtName.setBorder(null);
        jPanel2.add(TxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 250, 30));

        TxtMobNo.setBackground(new java.awt.Color(173, 192, 234));
        TxtMobNo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtMobNo.setBorder(null);
        jPanel2.add(TxtMobNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 290, 30));

        TxtMail.setBackground(new java.awt.Color(173, 192, 234));
        TxtMail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtMail.setBorder(null);
        jPanel2.add(TxtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 280, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Mail Address:-");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 150, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        lblJobId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJobId.setText("Phone No:-");
        jPanel2.add(lblJobId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 120, 20));

        PwdPanel.setOpaque(false);

        TxtConPwd.setBackground(new java.awt.Color(173, 192, 234));
        TxtConPwd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtConPwd.setBorder(null);

        TxtCurPwd.setBackground(new java.awt.Color(173, 192, 234));
        TxtCurPwd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtCurPwd.setBorder(null);

        TxtNewPwd.setBackground(new java.awt.Color(173, 192, 234));
        TxtNewPwd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtNewPwd.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("Current Password");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("New Password");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setText("Confirm Password");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N

        javax.swing.GroupLayout PwdPanelLayout = new javax.swing.GroupLayout(PwdPanel);
        PwdPanel.setLayout(PwdPanelLayout);
        PwdPanelLayout.setHorizontalGroup(
            PwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PwdPanelLayout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(PwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TxtNewPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(TxtCurPwd, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtConPwd))
                .addGap(22, 22, 22))
            .addGroup(PwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PwdPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(PwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PwdPanelLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(23, 23, 23)
                            .addComponent(jLabel16))
                        .addGroup(PwdPanelLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(50, 50, 50)
                            .addComponent(jLabel17))
                        .addGroup(PwdPanelLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(19, 19, 19)
                            .addComponent(jLabel19)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PwdPanelLayout.setVerticalGroup(
            PwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PwdPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(TxtCurPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(TxtNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(TxtConPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(PwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PwdPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(PwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16)
                        .addGroup(PwdPanelLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel13)))
                    .addGap(26, 26, 26)
                    .addGroup(PwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addGroup(PwdPanelLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel14)))
                    .addGap(26, 26, 26)
                    .addGroup(PwdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19)
                        .addGroup(PwdPanelLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel15)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(PwdPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 530, 210));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Want to change Password");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        CheckPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPwdActionPerformed(evt);
            }
        });
        jPanel2.add(CheckPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 10, 260));

        ResumePanel.setOpaque(false);

        jLabel10.setForeground(java.awt.Color.red);
        jLabel10.setText("* Upload Resume in within 1000Kb");

        TxtFilePath.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        BtnBrowserFile.setBackground(new java.awt.Color(204, 204, 255));
        BtnBrowserFile.setText("Browser File");
        BtnBrowserFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBrowserFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResumePanelLayout = new javax.swing.GroupLayout(ResumePanel);
        ResumePanel.setLayout(ResumePanelLayout);
        ResumePanelLayout.setHorizontalGroup(
            ResumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResumePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(ResumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(ResumePanelLayout.createSequentialGroup()
                        .addComponent(TxtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBrowserFile, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        ResumePanelLayout.setVerticalGroup(
            ResumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResumePanelLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBrowserFile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(ResumePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 700, 70));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Want to change Resume");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, 50));

        CheckResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckResumeActionPerformed(evt);
            }
        });
        jPanel2.add(CheckResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 30, 30));

        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 930, 130));

        BtnDiscardChanges.setBackground(new java.awt.Color(204, 204, 255));
        BtnDiscardChanges.setText("Discard Changes");
        BtnDiscardChanges.setOpaque(false);
        BtnDiscardChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDiscardChangesActionPerformed(evt);
            }
        });
        jPanel2.add(BtnDiscardChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 150, 30));

        BtnSaveChanges.setBackground(new java.awt.Color(204, 204, 255));
        BtnSaveChanges.setText("Saves Changes");
        BtnSaveChanges.setOpaque(false);
        BtnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveChangesActionPerformed(evt);
            }
        });
        jPanel2.add(BtnSaveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 670, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPwdActionPerformed
        if(CheckPwd.isSelected()){
            PwdPanel.setVisible(true);
        }
        else{
            PwdPanel.setVisible(false );
        }
    }//GEN-LAST:event_CheckPwdActionPerformed

    private void BtnBrowserFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBrowserFileActionPerformed
        JFileChooser fileChooser=new JFileChooser();
        fileChooser.setDialogTitle("Select Your Resume");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result=fileChooser.showOpenDialog(null);
        if(result==JFileChooser.APPROVE_OPTION){
            file=fileChooser.getSelectedFile();
            TxtFilePath.setText(file.getName());
        }
    }//GEN-LAST:event_BtnBrowserFileActionPerformed

    private void CheckResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckResumeActionPerformed
        if(CheckResume.isSelected()){
            ResumePanel.setVisible(true);
        }
        else{
            ResumePanel.setVisible(false);
        }
    }//GEN-LAST:event_CheckResumeActionPerformed

    private void BtnDiscardChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDiscardChangesActionPerformed
        new ParticipantsOptionFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnDiscardChangesActionPerformed

    private void BtnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveChangesActionPerformed
        boolean pwdChanged=false,resumeUpdated=false;
        if(CheckPwd.isSelected()){
            if(validateInputs()==false){
                JOptionPane.showMessageDialog(null, "Please Fill All The Fields","Empty Fields",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(matchPasswords()==false){
                JOptionPane.showMessageDialog(null, "Password And Confirm Password Do Not Match!","Password Mismatching",JOptionPane.WARNING_MESSAGE);
                return;
            }
            try{
                boolean resp=UserDAO.checkOldPassword(CurrentUser.getId(),oldpwd);
                if(resp==true){
                    UserDAO.updateParticipantPassword(CurrentUser.getId(), npwd);
                    pwdChanged=true;
                }else{
                    JOptionPane.showMessageDialog(null, "Your Old Password Is Wrong!","Password Mismatching",JOptionPane.WARNING_MESSAGE);
                }
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"DB Error In Edit Profile", "Error!!",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }

        }
        if(CheckResume.isSelected()){
            if(TxtFilePath.getText().trim()!=""){

                try{
                    ParticipantsDAO.updateResume(CurrentUser.getId(), file);
                    resumeUpdated=true;

                }
                catch(SQLException ex){
                    JOptionPane.showMessageDialog(null,"DB Error In Edit Profile", "Error!!",JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }
                catch(FileNotFoundException ex){
                    JOptionPane.showMessageDialog(null,"File Error In Edit Profile", "Error!!",JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }
            }
        }
        if(pwdChanged && resumeUpdated){
            JOptionPane.showMessageDialog(null, "Password & Resume Updated Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(pwdChanged){
            JOptionPane.showMessageDialog(null, "Password Updated Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(resumeUpdated){
            JOptionPane.showMessageDialog(null, "Resume Updated Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "No Changes Done!!","Message!",JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_BtnSaveChangesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PtEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PtEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PtEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PtEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PtEditProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBrowserFile;
    private javax.swing.JButton BtnDiscardChanges;
    private javax.swing.JButton BtnSaveChanges;
    private javax.swing.JCheckBox CheckPwd;
    private javax.swing.JCheckBox CheckResume;
    private javax.swing.JPanel PwdPanel;
    private javax.swing.JPanel ResumePanel;
    private javax.swing.JPasswordField TxtConPwd;
    private javax.swing.JPasswordField TxtCurPwd;
    private javax.swing.JTextField TxtFilePath;
    private javax.swing.JTextField TxtMail;
    private javax.swing.JTextField TxtMobNo;
    private javax.swing.JTextField TxtName;
    private javax.swing.JPasswordField TxtNewPwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblJobId;
    // End of variables declaration//GEN-END:variables

}
