/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trAndpl.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.swing.JOptionPane;
import trAndpl.Dao.QuestionDAO;
import trAndpl.Dao.ResultDAO;
import trAndpl.Dao.SendMails;
import trAndpl.pojo.CurrentUser;
import trAndpl.pojo.QuesPojo;
import trAndpl.pojo.ResultPojo;

/**
 *
 * @author Dell
 */
public class PtTakeQuizFrame extends javax.swing.JFrame {

    private String jobId;
    private String jobTitle;
    private QuesPojo currentQuestion;
    private int counter=0;
    private List<QuesPojo> questionList;
    private List<Integer> answerList;
    public PtTakeQuizFrame() {
        initComponents();
        setLocationRelativeTo(null);
        TimerScreen T=new TimerScreen();
        T.start();
      }
   class TimerScreen extends Thread
    {
        public void run()
        {
            int count=1;
            Random r = new Random();
            int timer=1*60;
            long delay = timer*1000;
            do{
                try{
                    int minute = timer/60;
                    int seconds=timer%60;
                    lblTimer.setText(minute+" m : "+seconds+" s");
                    Thread.sleep(1000);
                    timer=timer-1;
                    delay=delay-1000;
                }catch(InterruptedException ex){
                    JOptionPane.showMessageDialog(null, "Error in Take Test Frame", "Error", JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }
            }while(delay!=0);
             JOptionPane.showMessageDialog(null, "Times Up!\n Thanks for giving the test","Test Complete",JOptionPane.INFORMATION_MESSAGE);
             BtnSubmit.doClick(timer);
        }

    }
    public PtTakeQuizFrame(String jobId,String jobTitle) {
        this();
        this.jobId=jobId;
        this.jobTitle=jobTitle;
        lblTitle.setText("Paper For "+this.jobTitle);
        lblQno.setText(""+(counter+1));        
        this.setVisible(true);
        loadQuestionPaper();       
     }
    private void loadQuestionPaper(){
        try{
            questionList=QuestionDAO.getQuestionPaperByJobId(jobId);
            answerList=new ArrayList<>(questionList.size());
            for(int i=0;i<questionList.size();i++){
                 answerList.add(i,0);
            }
            showNextQuestionInFrame();
        }
        
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error In Quiz", "Error!!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }    
        private void showNextQuestionInFrame(){
        currentQuestion=questionList.get(counter);
        TxtQues.setText(currentQuestion.getQuestion());
        jrbOpt1.setText(currentQuestion.getOption1());
        jrbOpt2.setText(currentQuestion.getOption2());
        jrbOpt3.setText(currentQuestion.getOption3());
        jrbOpt4.setText(currentQuestion.getOption4());
        int answer=answerList.get(counter);
        switch(answer){
               case 1:
                        jrbOpt1.setSelected(true);
                        break;
               case 2:
                        jrbOpt2.setSelected(true);
                        break;
               case 3:
                        jrbOpt3.setSelected(true);
                        break;
               case 4:
                        jrbOpt4.setSelected(true);
                        break;
               default:
                        buttonGroup1.clearSelection();
           }   
        }
        private int validateChooseOption() 
       {
        if(jrbOpt1.isSelected())
            return 1;
        else if(jrbOpt2.isSelected())
            return 2;
        else if(jrbOpt3.isSelected())
            return 3;
        else if(jrbOpt4.isSelected())
            return 4;   
        else
            return 0;
    }
    private double getPercentage(){
        int marksObtained=0;
        for(int i=0;i<questionList.size();i++){
            QuesPojo question=questionList.get(i);
            if(question.getCorrectOption()==answerList.get(i)){
                ++marksObtained;
            }
        }
        double per=((double)marksObtained/questionList.size())*100;
        return per;
        
    }
  




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtnDiscard = new javax.swing.JButton();
        BtnNext = new javax.swing.JButton();
        BtnPrev = new javax.swing.JButton();
        BtnSubmit = new javax.swing.JButton();
        jrbOpt1 = new javax.swing.JRadioButton();
        jrbOpt2 = new javax.swing.JRadioButton();
        jrbOpt4 = new javax.swing.JRadioButton();
        jrbOpt3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtQues = new javax.swing.JTextArea();
        lblQno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 245, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/World-Map.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 960, 210));

        BtnDiscard.setBackground(new java.awt.Color(204, 204, 255));
        BtnDiscard.setText("Discard Paper");
        BtnDiscard.setOpaque(false);
        BtnDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDiscardActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDiscard, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 660, 130, -1));

        BtnNext.setBackground(new java.awt.Color(204, 204, 255));
        BtnNext.setText("Next");
        BtnNext.setOpaque(false);
        BtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNextActionPerformed(evt);
            }
        });
        jPanel1.add(BtnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, 120, -1));

        BtnPrev.setBackground(new java.awt.Color(204, 204, 255));
        BtnPrev.setText("Previous");
        BtnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrevActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 110, -1));

        BtnSubmit.setBackground(new java.awt.Color(204, 204, 255));
        BtnSubmit.setText("Submit");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 660, 120, -1));

        jrbOpt1.setBackground(new java.awt.Color(173, 192, 234));
        buttonGroup1.add(jrbOpt1);
        jrbOpt1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(jrbOpt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        jrbOpt2.setBackground(new java.awt.Color(173, 192, 234));
        buttonGroup1.add(jrbOpt2);
        jrbOpt2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(jrbOpt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, -1, -1));

        jrbOpt4.setBackground(new java.awt.Color(173, 192, 234));
        buttonGroup1.add(jrbOpt4);
        jrbOpt4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(jrbOpt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, -1, -1));

        jrbOpt3.setBackground(new java.awt.Color(173, 192, 234));
        buttonGroup1.add(jrbOpt3);
        jrbOpt3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(jrbOpt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, -1, -1));

        jLabel6.setFont(new java.awt.Font("Noteworthy", 1, 24)); // NOI18N
        jLabel6.setText("Options-");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noteworthy", 1, 12)); // NOI18N
        jLabel7.setText("Option 1");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 60, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Noteworthy", 1, 12)); // NOI18N
        jLabel10.setText("Option 3");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 60, -1));

        jLabel11.setFont(new java.awt.Font("Noteworthy", 1, 12)); // NOI18N
        jLabel11.setText("Option 4");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 60, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, -1));

        jLabel14.setFont(new java.awt.Font("Noteworthy", 1, 12)); // NOI18N
        jLabel14.setText("Option 2");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 60, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/2021-12-23 00.04.59.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, -1, -1));

        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 960, 190));

        jLabel3.setFont(new java.awt.Font("Noteworthy", 1, 24)); // NOI18N
        jLabel3.setText("Que.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        lblTitle.setFont(new java.awt.Font("Noteworthy", 1, 24)); // NOI18N
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 440, 40));

        TxtQues.setBackground(new java.awt.Color(173, 192, 234));
        TxtQues.setColumns(20);
        TxtQues.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtQues.setRows(5);
        jScrollPane1.setViewportView(TxtQues);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 850, 80));

        lblQno.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jPanel1.add(lblQno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 30, 40));

        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 960, 50));

        jLabel17.setBackground(new java.awt.Color(243, 245, 254));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 51));
        jLabel17.setText("Time Left:-");
        jLabel17.setOpaque(true);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 657, 80, 30));

        lblTimer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTimer.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDiscardActionPerformed
       int ans;
       ans= JOptionPane.showConfirmDialog(null, "Are You Sure Discard the Test?", "Discard!", JOptionPane.YES_NO_OPTION);
        if(ans==JOptionPane.YES_OPTION){
           new ParticipantsOptionFrame().setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_BtnDiscardActionPerformed

    private void BtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNextActionPerformed
        int res=validateChooseOption();
        if(res==0){
            JOptionPane.showMessageDialog(null,"Please Select An Option","No Option Selected!",JOptionPane.WARNING_MESSAGE);
            return;
        }
        answerList.set(counter, res);
        ++counter;
        if(counter==questionList.size()){
            counter=0;
        }
        showNextQuestionInFrame();
        lblQno.setText(""+(counter+1));  
        
                         


    }//GEN-LAST:event_BtnNextActionPerformed

    private void BtnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrevActionPerformed
       int res=validateChooseOption();
        if(res==0){
            JOptionPane.showMessageDialog(null,"Please Select An Option","No Option Selected!",JOptionPane.WARNING_MESSAGE);
            return;
        }
        answerList.set(counter, res);
        --counter;
        if(counter==-1){
            counter=questionList.size()-1;
        }
        showNextQuestionInFrame();
        lblQno.setText(""+(counter+1));  
                                               


    }//GEN-LAST:event_BtnPrevActionPerformed

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
        int res=validateChooseOption();
        if(res==0){
            JOptionPane.showMessageDialog(null,"Please Select An Option","No Option Selected!",JOptionPane.WARNING_MESSAGE);
            return;
        }
        answerList.set(counter, res);
        double per=getPercentage();
        ResultPojo result=new ResultPojo();
        result.setJobId(jobId);
        result.setpId(CurrentUser.getId());
        if(per<5)
            per=5.0;
        result.setPercentage(per);
        result.setSelectedByHr("No");
        try{
            boolean resp=ResultDAO.setResult(result);
            if(resp==true){
                JOptionPane.showMessageDialog(null,"You Got "+per+"% marks \nAnd Result Has Been Sent On Your Mail","Result!",JOptionPane.INFORMATION_MESSAGE);
                InternetAddress[]recipients=InternetAddress.parse(String.valueOf(CurrentUser.getUserId())+"");
                Message m=SendMails.Sends();
                m.setRecipients(Message.RecipientType.TO,recipients);
                m.setSubject("Notification From Tnp Application");
                m.setText("Hello "+CurrentUser.getName()+",\n"
                          + "\nYou got "+String.valueOf(result.getPercentage())+"% in "+jobId+" (\""+jobTitle+"\")"
                          +"\n\nWarm Regards"
                          +"\nSCALIVE "
                          +"\nTraning And Placement Application");
                Transport.send(m);
                new PtViewAllAppliedJobsFrame().setVisible(true);
                this.dispose();
            }
          }
       
        catch (MessagingException e) {
                   e.printStackTrace();
            }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error In Taake Test", "Error!!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        
        
         


    }//GEN-LAST:event_BtnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PtTakeQuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PtTakeQuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PtTakeQuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PtTakeQuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PtTakeQuizFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDiscard;
    private javax.swing.JButton BtnNext;
    private javax.swing.JButton BtnPrev;
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JTextArea TxtQues;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbOpt1;
    private javax.swing.JRadioButton jrbOpt2;
    private javax.swing.JRadioButton jrbOpt3;
    private javax.swing.JRadioButton jrbOpt4;
    private javax.swing.JLabel lblQno;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
