/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trAndpl.gui;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import trAndpl.Dao.ParticipantsDAO;
import trAndpl.pojo.ParticipantsPojo;

/**
 *
 * @author Dell
 */
public class SignUpFrame extends javax.swing.JFrame {

    private File file;
    private String pwd,cnfpwd;
    public SignUpFrame() {
        initComponents();
        setLocationRelativeTo(null);
        loadId();

    }
    private void loadId(){
        try{
            int pId=ParticipantsDAO.getNewParticipantId();
            lblPid.setText("P-"+pId);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error","Error In Generating HrID",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
        private boolean validateInputs(){
        char[]chpwd=TxtPwd.getPassword();
        char[]chnfPwd=TxtConPwd.getPassword();
        if(TxtName.getText().trim().isEmpty()||TxtMail.getText().trim().isEmpty()||TxtMob.getText().trim().isEmpty()||chpwd.length==0||chnfPwd.length==0||TxtSkill1.getText().trim().isEmpty()||TxtSkill2.getText().trim().isEmpty()||TxtSkill3.getText().trim().isEmpty()||TxtSkill4.getText().trim().isEmpty()||TxtResume.getText().trim().isEmpty()||TxtQualifications.getText().trim().isEmpty())
            return false;
        return true;
    }
    private void clearAll(){
        TxtName.setText("");
        TxtMob.setText("");
        TxtMail.setText("");
        TxtSkill1.setText("");
        TxtSkill2.setText("");
        TxtSkill3.setText("");
        TxtSkill4.setText("");
        TxtPwd.setText("");
        TxtConPwd.setText("");
        TxtResume.setText("");
        TxtQualifications.setText("");
    }
    private boolean matchPasswords(){
        pwd =String.valueOf(TxtPwd.getPassword());
        cnfpwd=String.valueOf(TxtConPwd.getPassword());
        return pwd.equals(cnfpwd);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtQualifications = new javax.swing.JTextField();
        TxtSkill3 = new javax.swing.JTextField();
        TxtPwd = new javax.swing.JPasswordField();
        TxtConPwd = new javax.swing.JPasswordField();
        TxtMail = new javax.swing.JTextField();
        TxtName = new javax.swing.JTextField();
        TxtMob = new javax.swing.JTextField();
        TxtSkill4 = new javax.swing.JTextField();
        TxtSkill2 = new javax.swing.JTextField();
        TxtSkill1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtnLoginPage = new javax.swing.JButton();
        BtnCreateAcc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPid = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TxtResume = new javax.swing.JTextField();
        BtnBrowserFile = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 245, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtQualifications.setBackground(new java.awt.Color(173, 192, 234));
        TxtQualifications.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(TxtQualifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 940, 50));

        TxtSkill3.setBackground(new java.awt.Color(173, 192, 234));
        TxtSkill3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(TxtSkill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 210, 30));

        TxtPwd.setBackground(new java.awt.Color(173, 192, 234));
        TxtPwd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtPwd.setBorder(null);
        jPanel1.add(TxtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 390, -1));

        TxtConPwd.setBackground(new java.awt.Color(173, 192, 234));
        TxtConPwd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtConPwd.setBorder(null);
        jPanel1.add(TxtConPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 370, -1));

        TxtMail.setBackground(new java.awt.Color(173, 192, 234));
        TxtMail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtMail.setBorder(null);
        jPanel1.add(TxtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 350, 20));

        TxtName.setBackground(new java.awt.Color(173, 192, 234));
        TxtName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtName.setBorder(null);
        jPanel1.add(TxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 390, -1));

        TxtMob.setBackground(new java.awt.Color(173, 192, 234));
        TxtMob.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtMob.setBorder(null);
        TxtMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMobActionPerformed(evt);
            }
        });
        jPanel1.add(TxtMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 350, 20));

        TxtSkill4.setBackground(new java.awt.Color(173, 192, 234));
        TxtSkill4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(TxtSkill4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 210, 30));

        TxtSkill2.setBackground(new java.awt.Color(173, 192, 234));
        TxtSkill2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtSkill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSkill2ActionPerformed(evt);
            }
        });
        jPanel1.add(TxtSkill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 190, 30));

        TxtSkill1.setBackground(new java.awt.Color(173, 192, 234));
        TxtSkill1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(TxtSkill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 170, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/World-Map.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 960, 210));

        BtnLoginPage.setBackground(new java.awt.Color(204, 204, 255));
        BtnLoginPage.setText("Login Page");
        BtnLoginPage.setOpaque(false);
        BtnLoginPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginPageActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLoginPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 170, 30));

        BtnCreateAcc.setBackground(new java.awt.Color(204, 204, 255));
        BtnCreateAcc.setText("Create Account");
        BtnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateAccActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCreateAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 690, 180, 30));

        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 1000, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Name:-");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 180, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Skills:-");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 170, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Participant id:-");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 30));

        lblPid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(lblPid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 70, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Qualifications:-");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 170, -1));

        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 1000, 170));

        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 470, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Mobile No:-");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Email id:-");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Upload Resume");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("Password:-");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Confirm Password:-");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, -1, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 460, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        TxtResume.setBackground(new java.awt.Color(173, 192, 234));
        TxtResume.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(TxtResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 230, 30));

        BtnBrowserFile.setBackground(new java.awt.Color(204, 204, 255));
        BtnBrowserFile.setText("Browser FILE");
        BtnBrowserFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBrowserFileActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBrowserFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 140, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trAndpl/Images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginPageActionPerformed
       new LoginFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnLoginPageActionPerformed

    private void BtnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateAccActionPerformed
                if(validateInputs()==false){
            JOptionPane.showMessageDialog(null,"Please input all the fields","Incomplete Data!",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(matchPasswords()==false){
            JOptionPane.showMessageDialog(null,"Passwords do not match","Mismatched Passwords!",JOptionPane.WARNING_MESSAGE);
            return;
        }
        try{
            ParticipantsPojo pt=new ParticipantsPojo();
            pt.setId(lblPid.getText().trim());
            pt.setUserId(TxtMail.getText().trim().toUpperCase());
            pt.setName(TxtName.getText().trim());
            pt.setPhone(TxtMob.getText().trim());
            pt.setResume(file);
            pt.setSkills(TxtSkill1.getText().trim()+","+TxtSkill2.getText().trim()+","+TxtSkill3.getText().trim()+","+TxtSkill4.getText().trim());
            pt.setQualifications(TxtQualifications.getText().trim());
            pt.setPassword(pwd);
            pt.setType("Students");
            int result=ParticipantsDAO.addNewParticipant(pt);
            if(result==1){
                 JOptionPane.showMessageDialog(null,"Participant Added Successfully!","Success!!",JOptionPane.INFORMATION_MESSAGE);
                 clearAll();
                 loadId();
                 return;
            }else if(result==-1){
                JOptionPane.showMessageDialog(null,"Email-Id Already Taken!","Registration Failed!",JOptionPane.ERROR_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,"Cannot Add The Record!","Registration Failed!",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"SQL Error!","DB Problem,",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            return;
        }
        catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null,"File Error!","File Problem,",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            return;
        }
                  

    }//GEN-LAST:event_BtnCreateAccActionPerformed

    private void TxtSkill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSkill2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSkill2ActionPerformed

    private void TxtMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMobActionPerformed

    private void BtnBrowserFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBrowserFileActionPerformed
       JFileChooser fileChooser=new JFileChooser();
       fileChooser.setDialogTitle("Select Your Resume");
       fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
       int result=fileChooser.showOpenDialog(null);
       if(result==JFileChooser.APPROVE_OPTION){
           file=fileChooser.getSelectedFile();
           TxtResume.setText(file.getName());
       }

    }//GEN-LAST:event_BtnBrowserFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBrowserFile;
    private javax.swing.JButton BtnCreateAcc;
    private javax.swing.JButton BtnLoginPage;
    private javax.swing.JPasswordField TxtConPwd;
    private javax.swing.JTextField TxtMail;
    private javax.swing.JTextField TxtMob;
    private javax.swing.JTextField TxtName;
    private javax.swing.JPasswordField TxtPwd;
    private javax.swing.JTextField TxtQualifications;
    private javax.swing.JTextField TxtResume;
    private javax.swing.JTextField TxtSkill1;
    private javax.swing.JTextField TxtSkill2;
    private javax.swing.JTextField TxtSkill3;
    private javax.swing.JTextField TxtSkill4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPid;
    // End of variables declaration//GEN-END:variables
}
